website/tasks/urls.py
from django.urls import path
from . import views

# namespace
app_name = "tasks"

urlpatterns = [
    # Retrieve task list
    path("", views.task_list, name="task_list"),
    # Create new task
    path("create/", views.task_create, name="task_create"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
]

website/tasks/models.py
from django.db import models

class Status(models.TextChoices):
    UNSTARTED = 'u', "Not started yet"
    ONGOING = 'o', "Ongoing"
    FINISHED = 'f', "Finished"

# Task模型
class Task(models.Model):
    name = models.CharField(verbose_name="Task name", max_length=65, unique=True)
    status = models.CharField(verbose_name="Task status", max_length=1, choices=Status.choices)

    def __str__(self):
        return self.name

website/tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'status']

website/tasks/views.py
# tasks/views.py

from django.shortcuts import render, redirect
from .models import Task
from .forms import TaskForm

# 任务清单
def task_list(request):
    # 从数据库获取Task对象列表
    tasks = Task.objects.all()
    # 指定渲染模板并向模板传递数据
    return render(request, "tasks/task_list.html", {"tasks": tasks})

# 任务创建
def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:task_list')
    else:
        form = TaskForm()
    return render(request, 'tasks/task_form.html', {'form': form})

website/tasks/templates/tasks/task_form.html
<!-- tasks/templates/tasks/task_form.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Task</title>
</head>
<body>
    <h3>Create New Task</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Task</button>
    </form>
</body>
</html>

website/tasks/templates/tasks/task_list.html
<!-- tasks/templates/tasks/task_list.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task List</title>
</head>
<body>
    <h3>Task List</h3>
    <a href="{% url 'tasks:task_create' %}">Create New Task</a>
    {% for task in tasks %}
    <p>{{ forloop.counter }}. {{ task.name }} - {{ task.get_status_display }}</p>
    {% endfor %}
</body>
</html>